## 결측값 처리와 조건에 맞는 행 선택

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 10)

df = pd.DataFrame({'age':[25, np.nan, 42, 31], 'gender':['여성','남성','남성','여성']})
df['age'] = df['age'].fillna(df['age'].mean())
df

         age gender
0  25.000000     여성
1  32.666667     남성
2  42.000000     남성
3  31.000000     여성

In [2]:
df[(df['age'] >= 30) & (df['gender'] == '남성')]

         age gender
1  32.666667     남성
2  42.000000     남성